import Head from "next/head";
import React from "react";
import { useState } from "react";
import AreaChart from "../components/AreaChart";

export default function Home() {
  const [term, setTerm] = useState(0);
  const [xaxis, setXaxis] = useState();
  const [yaxis, setYaxis] = useState();
  const [data, setData] = useState([]);
  const storeData = () => {
    setData((oldData) => [...oldData, { xaxis, yaxis, timestamp: Date.now() }]);
    setXaxis("");
    setYaxis("");
  };
  console.log(data);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className=" text-center my-5 text-2xl uppercase font-bold">
        Welcome to the Sujan Graph Analyzer
      </h1>

      <div className="flex items-center justify-center">
        <form action="">
          <input
            type="text"
            placeholder="Enter the no of Term"
            className="text-center focus:outline-none text-black px-3 py-3 my-5"
            onChange={(e) => setTerm(e.target.value)}
          />
          <span
            className=" px-3 py-3 bg-gradient-to-r
           from-green-400 to-blue-500 hover:from-pink-500 hover:to-yellow-500 cursor-pointer"
            onClick={() => setTable(term)}
          >
            Proceed
          </span>
        </form>
      </div>

      <div className="flex flex-col items-center justify-center mt-5">
        <div>
          <button className=" px-5 bg-gradient-to-r from-indigo-500 mx-5">
            {" "}
            X axis
          </button>
          <button className=" px-5 bg-gradient-to-r from-indigo-500 mx-5">
            {" "}
            y axis
          </button>
        </div>
        <div>
          <form action="">
            <input
              type="text"
              value="Time"
              disabled
              className="mx-3 py-3 text-center bg-gradient-to-r from-indigo-500"
            />
            <input
              type="text"
              value="Price"
              disabled
              className="mx-3 py-3 text-center bg-gradient-to-r from-indigo-500"
            />
          </form>
        </div>

        <div>
          <form action="">
            <div className=" flex">
              <input
                type="text"
                placeholder="Enter the value"
                className="text-black focus:outline-none mx-3 py-3 text-center bg-white border-b-4 border-indigo-500"
                value={xaxis}
                onChange={(e) => setXaxis(e.target.value)}
              />
              <input
                type="text"
                placeholder="Enter the value"
                className=" text-black focus:outline-none mx-3 py-3 text-center bg-white border-b-4 border-indigo-500"
                value={yaxis}
                onChange={(e) => setYaxis(e.target.value)}
              />
              <span
                className="px-3 py-3 bg-gradient-to-r
           from-green-400 to-blue-500 hover:from-pink-500 hover:to-yellow-500 cursor-pointer border-b-4 border-indigo-500"
                onClick={() => storeData()}
              >
                Submit
              </span>
            </div>

            {data.map((e) => {
              return (
                <div className=" flex">
                  <input
                    type="text"
                    placeholder="Enter the value"
                    className="text-black focus:outline-none mx-3 py-3 text-center bg-green-400 border-b-4 border-indigo-500"
                    value={e.xaxis}
                    disabled
                  />
                  <input
                    type="text"
                    placeholder="Enter the value"
                    className=" text-black focus:outline-none mx-3 py-3 text-center bg-sky-400 border-b-4 border-indigo-500"
                    value={e.yaxis}
                    disabled
                  />
                </div>
              );
            })}
          </form>
        </div>
      </div>
    </div>
  );
}
